CREATE TYPE "public"."user_role" AS ENUM('sys_admin', 'org_admin', 'org_user');--> statement-breakpoint
CREATE TYPE "public"."notification_battery_state" AS ENUM('low', 'critical');--> statement-breakpoint
CREATE TYPE "public"."notification_type" AS ENUM('low_stock', 'low_battery');--> statement-breakpoint
CREATE TYPE "public"."shelf_position_log_type" AS ENUM('refill', 'auto_check');--> statement-breakpoint
CREATE TABLE "product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric(9, 2) NOT NULL,
	"deleted_at" timestamp DEFAULT NULL
);
--> statement-breakpoint
CREATE TABLE "product_discount" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_discount_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"new_price" numeric(9, 2) NOT NULL,
	"discount_percent" integer NOT NULL,
	"valid_from" date NOT NULL,
	"valid_until" date NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "minmax_discount_percent_check" CHECK ("product_discount"."discount_percent" >= 0 AND "product_discount"."discount_percent" <= 100)
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "user_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" integer,
	"role" "user_role" NOT NULL,
	"email" varchar(255) NOT NULL,
	"password_hash" varchar(130) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "user_refresh_token" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "user_refresh_token_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"jti" varchar(72) NOT NULL,
	"created_at" timestamp DEFAULT NOW() NOT NULL,
	"valid_until" timestamp NOT NULL,
	"revoked_at" timestamp DEFAULT NULL
);
--> statement-breakpoint
CREATE TABLE "notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" integer NOT NULL,
	"type" "notification_type" NOT NULL,
	"created_at" timestamp DEFAULT NOW() NOT NULL,
	"read_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "notification_low_battery" (
	"id" integer PRIMARY KEY NOT NULL,
	"shelf_position_device_id" integer NOT NULL,
	"battery_state" "notification_battery_state" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notification_low_stock" (
	"id" integer PRIMARY KEY NOT NULL,
	"shelf_position_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"remaining_amount_percent" integer NOT NULL,
	CONSTRAINT "minmax_amount_percent" CHECK ("notification_low_stock"."remaining_amount_percent" >= 0 AND "notification_low_stock"."remaining_amount_percent" <= 100)
);
--> statement-breakpoint
CREATE TABLE "shelf" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shelf_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" integer NOT NULL,
	"device_id" integer NOT NULL,
	"shelf_name" varchar(255) NOT NULL,
	"shelf_store_location" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "shelf_position" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shelf_position_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shelf_id" integer NOT NULL,
	"product_id" integer,
	"row" integer NOT NULL,
	"column" integer NOT NULL,
	"low_stock_threshold_percent" integer DEFAULT 20 NOT NULL,
	"max_current_product_capacity" integer,
	CONSTRAINT "row_column_shelf_unique" UNIQUE("shelf_id","row","column"),
	CONSTRAINT "minmax_low_stock_threshold" CHECK ("shelf_position"."low_stock_threshold_percent" > 0 AND "shelf_position"."low_stock_threshold_percent" < 100),
	CONSTRAINT "min_product_capacity" CHECK ("shelf_position"."max_current_product_capacity" > 0)
);
--> statement-breakpoint
CREATE TABLE "shelf_position_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shelf_position_log_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" "shelf_position_log_type" NOT NULL,
	"user_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"shelf_position_id" integer NOT NULL,
	"timestamp" timestamp DEFAULT NOW() NOT NULL,
	"amount_percent" integer NOT NULL,
	CONSTRAINT "minmax_amount_percent" CHECK ("shelf_position_log"."amount_percent" >= 0 AND "shelf_position_log"."amount_percent" <= 100)
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "organization_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "shelf_device" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shelf_device_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"serial_number" varchar(255) NOT NULL,
	"device_secret" char(72) NOT NULL,
	"current_battery_percent" integer,
	"last_connected" timestamp,
	CONSTRAINT "shelf_device_serial_number_unique" UNIQUE("serial_number"),
	CONSTRAINT "valid_battery_range_check" CHECK ("shelf_device"."current_battery_percent" >= 0 AND "shelf_device"."current_battery_percent" <= 100)
);
--> statement-breakpoint
CREATE TABLE "shelf_device_status_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shelf_device_status_log_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shelf_device_id" integer NOT NULL,
	"timestamp" timestamp DEFAULT NOW() NOT NULL,
	"battery_percent" integer NOT NULL,
	CONSTRAINT "valid_battery_range_check" CHECK ("shelf_device_status_log"."battery_percent" >= 0 AND "shelf_device_status_log"."battery_percent" <= 100)
);
--> statement-breakpoint
ALTER TABLE "product" ADD CONSTRAINT "product_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "product_discount" ADD CONSTRAINT "product_discount_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user" ADD CONSTRAINT "user_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user_refresh_token" ADD CONSTRAINT "user_refresh_token_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notification" ADD CONSTRAINT "notification_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notification_low_battery" ADD CONSTRAINT "notification_low_battery_id_notification_id_fk" FOREIGN KEY ("id") REFERENCES "public"."notification"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notification_low_battery" ADD CONSTRAINT "notification_low_battery_shelf_position_device_id_shelf_device_id_fk" FOREIGN KEY ("shelf_position_device_id") REFERENCES "public"."shelf_device"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_low_stock" ADD CONSTRAINT "notification_low_stock_id_notification_id_fk" FOREIGN KEY ("id") REFERENCES "public"."notification"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notification_low_stock" ADD CONSTRAINT "notification_low_stock_shelf_position_id_shelf_position_id_fk" FOREIGN KEY ("shelf_position_id") REFERENCES "public"."shelf_position"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notification_low_stock" ADD CONSTRAINT "notification_low_stock_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "shelf" ADD CONSTRAINT "shelf_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "shelf" ADD CONSTRAINT "shelf_device_id_shelf_device_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."shelf_device"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "shelf_position" ADD CONSTRAINT "shelf_position_shelf_id_shelf_id_fk" FOREIGN KEY ("shelf_id") REFERENCES "public"."shelf"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shelf_position" ADD CONSTRAINT "shelf_position_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "shelf_position_log" ADD CONSTRAINT "shelf_position_log_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "shelf_position_log" ADD CONSTRAINT "shelf_position_log_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shelf_position_log" ADD CONSTRAINT "shelf_position_log_shelf_position_id_shelf_position_id_fk" FOREIGN KEY ("shelf_position_id") REFERENCES "public"."shelf_position"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shelf_device_status_log" ADD CONSTRAINT "shelf_device_status_log_shelf_device_id_shelf_device_id_fk" FOREIGN KEY ("shelf_device_id") REFERENCES "public"."shelf_device"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "prod_price_idx" ON "product" USING btree ("price");--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_product_name_org" ON "product" USING btree ("name","organization_id");--> statement-breakpoint
CREATE INDEX "prod_disc_valid_from_idx" ON "product_discount" USING btree ("valid_from" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "prod_disc_valid_until_idx" ON "product_discount" USING btree ("valid_until" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "notification_created_idx" ON "notification" USING btree ("created_at" DESC NULLS LAST);