CREATE TABLE "shelf_positions_device" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shelf_positions_device_id_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gateway_device_id" integer NOT NULL,
	"serial_number" varchar(255) NOT NULL,
	"number_of_slots" integer NOT NULL,
	"current_battery_percent" integer DEFAULT NULL,
	CONSTRAINT "shelf_positions_device_serial_number_unique" UNIQUE("serial_number"),
	CONSTRAINT "valid_battery_range_check" CHECK ("shelf_positions_device"."current_battery_percent" >= 0 AND "shelf_positions_device"."current_battery_percent" <= 100),
	CONSTRAINT "number_of_slots_min_check" CHECK ("shelf_positions_device"."number_of_slots" >= 1)
);
--> statement-breakpoint
CREATE TABLE "shelf_positions_device_pairing" (
	"shelf_positions_device_id" integer NOT NULL,
	"slot_number" integer NOT NULL,
	"pairing_code" varchar(8),
	"shelf_position_id" integer,
	"nfc_tag" varchar,
	CONSTRAINT "shelf_positions_device_pairing_shelf_positions_device_id_slot_number_pk" PRIMARY KEY("shelf_positions_device_id","slot_number"),
	CONSTRAINT "shelf_positions_device_pairing_pairing_code_unique" UNIQUE("pairing_code"),
	CONSTRAINT "shelf_positions_device_pairing_nfc_tag_unique" UNIQUE("nfc_tag")
);
--> statement-breakpoint
ALTER TABLE "shelf_device" RENAME TO "gateway_device";--> statement-breakpoint
ALTER TABLE "shelf_device_status_log" RENAME TO "shelf_positions_device_status_log";--> statement-breakpoint
ALTER TABLE "notification_low_battery" RENAME COLUMN "shelf_position_device_id" TO "shelf_positions_device_id";--> statement-breakpoint
ALTER TABLE "shelf_positions_device_status_log" RENAME COLUMN "shelf_device_id" TO "shelf_positions_device_id";--> statement-breakpoint
ALTER TABLE "gateway_device" DROP CONSTRAINT "shelf_device_serial_number_unique";--> statement-breakpoint
ALTER TABLE "gateway_device" DROP CONSTRAINT "valid_battery_range_check";--> statement-breakpoint
ALTER TABLE "shelf_positions_device_status_log" DROP CONSTRAINT "valid_battery_range_check";--> statement-breakpoint
ALTER TABLE "notification_low_battery" DROP CONSTRAINT "notification_low_battery_shelf_position_device_id_shelf_device_id_fk";
--> statement-breakpoint
ALTER TABLE "shelf" DROP CONSTRAINT "shelf_device_id_shelf_device_id_fk";
--> statement-breakpoint
ALTER TABLE "shelf_positions_device_status_log" DROP CONSTRAINT "shelf_device_status_log_shelf_device_id_shelf_device_id_fk";
--> statement-breakpoint
ALTER TABLE "notification" ALTER COLUMN "organization_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "shelf_positions_device" ADD CONSTRAINT "shelf_positions_device_gateway_device_id_gateway_device_id_fk" FOREIGN KEY ("gateway_device_id") REFERENCES "public"."gateway_device"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "shelf_positions_device_pairing" ADD CONSTRAINT "shelf_positions_device_pairing_shelf_positions_device_id_shelf_positions_device_id_fk" FOREIGN KEY ("shelf_positions_device_id") REFERENCES "public"."shelf_positions_device"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "shelf_positions_device_pairing" ADD CONSTRAINT "shelf_positions_device_pairing_shelf_position_id_shelf_position_id_fk" FOREIGN KEY ("shelf_position_id") REFERENCES "public"."shelf_position"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "notification_low_battery" ADD CONSTRAINT "notification_low_battery_shelf_positions_device_id_shelf_positions_device_id_fk" FOREIGN KEY ("shelf_positions_device_id") REFERENCES "public"."shelf_positions_device"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shelf_positions_device_status_log" ADD CONSTRAINT "shelf_positions_device_status_log_shelf_positions_device_id_shelf_positions_device_id_fk" FOREIGN KEY ("shelf_positions_device_id") REFERENCES "public"."shelf_positions_device"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "last_connected_from_newest_idx" ON "gateway_device" USING btree ("last_connected" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "timestamp_from_newest_idx" ON "shelf_positions_device_status_log" USING btree ("timestamp" DESC NULLS LAST);--> statement-breakpoint
ALTER TABLE "shelf" DROP COLUMN "device_id";--> statement-breakpoint
ALTER TABLE "gateway_device" DROP COLUMN "current_battery_percent";--> statement-breakpoint
ALTER TABLE "gateway_device" ADD CONSTRAINT "gateway_device_serial_number_unique" UNIQUE("serial_number");--> statement-breakpoint
ALTER TABLE "shelf_positions_device_status_log" ADD CONSTRAINT "valid_battery_range_check" CHECK ("shelf_positions_device_status_log"."battery_percent" >= 0 AND "shelf_positions_device_status_log"."battery_percent" <= 100);